{
  navbar {
    name
    logo
  }
  hero {
    logo
    header
    video
  }
  about {
    name
    header
    content
    image
  }
  slideshow {
    header
    images {
      image
    }
  }
  residences {
    content
    pdf
    cards {
      card {
        header
        content
        image
        list
      }
    }
  }
  amenities {
    header
    cards {
      card {
        header
        content
        image
      }
    }
  }
  info {
    header
    content
    images {
      image
    }
  }
  # headers array needs to be in sync with content array: headers length === values length + 1 (because of pdf),
  # content of value[x] falls under headers[x]
  availability {
    headers {
      header
    }
    rows {
      row {
        values {
          content
        }
        pdf
      }
    }
  }
  inquire {
    logo
    email
    phone
    address
    names {
      name
    }
    prices {
      range
    }
  }
  footer {
    logos {
      image
    }
  }
}
